module.exports = {
  architectureA: "Agnostic",
  architectureSp: "Specific",
  architectureHy: "Hybrid",
  architectureSpSi: "Specific singleton",
  architectureHySi: "Hybrid singleton",
  recoveryOnchain: "Onchain recovery",
  recoveryOffchain: "Offchain recovery",
  walletHW: "Half wallet",
  walletFW: "Full wallet",
  execD: "Deployment",
  execOR: "Offchain recovery",
  execORFC: "Offchain recovery fast close",
  execA: "Agnostic",
  execAFC: "Agnostic fast close",
  execSp: "Specific",
  execSpFC: "Specific fast close",
  execHy: "Hybrid",
  execHyFC: "Hybrid fast close",
  execHyWR: "Hybrid with relock",
  execSpSi: "Specific singleton",
  execSpSiFC: "Specific singleton fast close",
  execHySi: "Hybrid singleton",
  execHySiFC: "Hybrid singleton fast close",
  execHySiWR: "Hybrid singleton with relock",
  execHW: "Half wallet",
  execFW: "Full wallet",
  correctE: "Correct E",
  guessN: "Guess N",
  wrongN: "Wrong N",
  guessS: "Guess S",
  correctS: "Correct S (1 hit)",
  guessA: "Guess A",
  wrongA: "Wrong A",
  guessT: "Guess T",
  correctT: "Correct T (2 hits)",
  close: "Close",
  fastClose: "Fast closing",
  startDispute: "Start Dispute",
  updateDispute: "Update Dispute",
  submitEvidence: "Provide more current evidence",
  finalizeDispute: "Finalize Dispute",
  initializeChannel: "Initialize new channel instance",
  lock: "Locking instance",
  unlock: "Unlocking isntance",
  evidence: "Provide evidence",
  transfer: "Transfer funds",
  submitTx: "Submit transaction",
  executeTx: "Execute installation",
  executePayout: "Execute payout",
  revokeTxWithPayout: "Devalidate transaction",
  revokeTxWithoutPayout: "Devalidate transaction without payout",
  updateNonce: "Update nonce",
  deployOR: "Deploy Offchain Recovery",
  deployHy: "Deploy Hyrbid Channel",
  deployHySi: "Deploy Hyrbid Singleton",
  deployDB: "Deploy Hybrid Dispute Board",
  deploySp: "Deploy Specific Channel",
  deploySpSi: "Deploy Specific Singleton",
  deployA: "Deploy Agnostic Channel Manager",
  deployL: "Deploy Hangman Library",
  deployHW: "Deploy Half Multi App Wallet",
  deployFW: "Deploy Full Multi App Wallet"
}
